library(readr)
library(dplyr)
library(xlsx)
hours <- read_csv("C:/Users/WEI/Desktop/R/hours.csv")
na.omit(hours)
Nhours<-hours%>%filter(類別=="地方文化局")%>%select(年度,項目,小時總數)%>%filter(年度>=2012)%>%arrange(desc(年度))
budget2 <- read_csv("C:/Users/WEI/Desktop/R/budget2.csv")
na.omit(budget2)
Nbudget2 <- budget2%>%filter(年度>=2012)%>%select(文化局占地方政府總預算比率)
place <- read_csv("C:/Users/WEI/Desktop/R/歷年 全國展演場地.csv")
na.omit(place)
Nplace<-place%>%select(年度,文化展演場地合計,人口)%>%mutate(每萬人均場地數=文化展演場地合計/人口*10000)%>%filter(年度>=2012)%>%select(每萬人均場地數)
gov<-cbind.data.frame(Nhours,Nbudget2)
gov<-cbind.data.frame(gov,Nplace)
write.csv(gov,file="C:\\Users\\WEI\\Desktop\\R\\政府投入指標.csv",row.names = FALSE)
write.xlsx(gov,file="C:\\Users\\WEI\\Desktop\\R\\政府投入指標.xlsx",row.names = FALSE)